# enabled: true or false to disable the plugin
enabled: true

# Accounts Admin plugin priority
priority: 50

# Is super admin registered
supper_admin_registered: false

# From email
from:
  email: support@flextype.org
