# enabled: true or false to disable the plugin
enabled: true

# Accounts Admin plugin priority
priority: 90

# Is super admin registered
supper_admin_registered: false

# From email
from:
  name: Flextype
  email: sergey.romanenko@flextype.org
